-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.appointment_open_slots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL UNIQUE,
  tenant_id uuid NOT NULL,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT appointment_open_slots_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_open_slots_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.appointment_waitlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  person_id uuid NOT NULL,
  customer_profile_id uuid NOT NULL,
  service_title text,
  preferred_staff_id uuid,
  preferred_days jsonb,
  time_from time without time zone,
  time_to time without time zone,
  notes text,
  priority text DEFAULT 'normal'::text,
  status text DEFAULT 'active'::text,
  booked_appointment_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  short_notice_ok boolean NOT NULL DEFAULT false,
  reachable_today boolean NOT NULL DEFAULT false,
  requested_recently_at timestamp with time zone,
  CONSTRAINT appointment_waitlist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  person_id uuid,
  service_id uuid,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  notes_internal text,
  google_calendar_id text,
  google_event_id text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  buffer_minutes integer NOT NULL DEFAULT 0,
  reminder_at timestamp with time zone,
  reminder_sent_at timestamp with time zone,
  service_name_snapshot text,
  service_price_cents_snapshot integer,
  service_duration_minutes_snapshot integer,
  service_buffer_minutes_snapshot integer,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT appointments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_locations (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  street text,
  zip text,
  city text,
  country_code text NOT NULL DEFAULT 'AT'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cash_registers (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  location_id text,
  current_signature_unit_id text,
  register_code text NOT NULL,
  name text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::cash_register_status,
  finanzonline_registered_at timestamp with time zone,
  activated_at timestamp with time zone,
  deactivated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cash_registers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cash_registers_location FOREIGN KEY (location_id) REFERENCES public.business_locations(id),
  CONSTRAINT fk_cash_registers_current_signature FOREIGN KEY (current_signature_unit_id) REFERENCES public.signature_units(id)
);
CREATE TABLE public.cash_registers_backup_20260407 (
  id text,
  tenant_id text,
  location_id text,
  current_signature_unit_id text,
  register_code text,
  name text,
  status USER-DEFINED,
  finanzonline_registered_at timestamp with time zone,
  activated_at timestamp with time zone,
  deactivated_at timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.credit_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  credit_number text NOT NULL,
  original_invoice_id uuid NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  reason text NOT NULL,
  total_cents integer NOT NULL DEFAULT 0,
  pdf_storage_path text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT credit_notes_original_invoice_id_fkey FOREIGN KEY (original_invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_profile_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  created_by uuid NOT NULL,
  note text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_notes_pkey PRIMARY KEY (id),
  CONSTRAINT customer_notes_customer_profile_id_fkey FOREIGN KEY (customer_profile_id) REFERENCES public.customer_profiles(id),
  CONSTRAINT customer_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_profile_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  created_by uuid NOT NULL,
  storage_path text NOT NULL,
  original_name text,
  mime_type text,
  size_bytes bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_photos_pkey PRIMARY KEY (id),
  CONSTRAINT customer_photos_customer_profile_id_fkey FOREIGN KEY (customer_profile_id) REFERENCES public.customer_profiles(id),
  CONSTRAINT customer_photos_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  person_id uuid NOT NULL,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT customer_profiles_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT customer_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  person_id uuid,
  customer_profile_id uuid,
  appointment_id uuid,
  type text NOT NULL,
  file_path text NOT NULL,
  file_name text,
  mime_type text,
  size_bytes bigint,
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT files_pkey PRIMARY KEY (id),
  CONSTRAINT files_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT files_customer_profile_id_fkey FOREIGN KEY (customer_profile_id) REFERENCES public.customer_profiles(id),
  CONSTRAINT files_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT files_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.fiscal_event_failures (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text,
  cash_register_id text,
  sales_order_id text,
  payment_id text,
  fiscal_receipt_id text,
  failed_step text NOT NULL,
  error_message text NOT NULL,
  error_detail jsonb,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fiscal_event_failures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fiscal_events (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  cash_register_id text,
  signature_unit_id text,
  fiscal_receipt_id text,
  event_type USER-DEFINED NOT NULL,
  event_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  performed_by text,
  reference_data jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fiscal_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_fiscal_events_cash_register FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id),
  CONSTRAINT fk_fiscal_events_fiscal_receipt FOREIGN KEY (fiscal_receipt_id) REFERENCES public.fiscal_receipts(id)
);
CREATE TABLE public.fiscal_receipt_lines (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  fiscal_receipt_id text NOT NULL,
  source_line_id text,
  name text NOT NULL,
  quantity numeric NOT NULL,
  unit_price_gross numeric NOT NULL,
  tax_rate numeric NOT NULL,
  line_total_gross numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fiscal_receipt_lines_pkey PRIMARY KEY (id),
  CONSTRAINT fk_fiscal_receipt_lines_receipt FOREIGN KEY (fiscal_receipt_id) REFERENCES public.fiscal_receipts(id)
);
CREATE TABLE public.fiscal_receipts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  cash_register_id text NOT NULL,
  sales_order_id text,
  invoice_id text,
  payment_id text,
  receipt_number text NOT NULL,
  receipt_type USER-DEFINED NOT NULL DEFAULT 'STANDARD'::fiscal_receipt_type,
  status USER-DEFINED NOT NULL DEFAULT 'REQUESTED'::fiscal_receipt_status,
  issued_at timestamp with time zone,
  currency_code text NOT NULL DEFAULT 'EUR'::text,
  sum_tax_set_normal numeric NOT NULL DEFAULT 0,
  sum_tax_set_reduced1 numeric NOT NULL DEFAULT 0,
  sum_tax_set_reduced2 numeric NOT NULL DEFAULT 0,
  sum_tax_set_zero numeric NOT NULL DEFAULT 0,
  turnover_value_cents integer NOT NULL DEFAULT 0,
  machine_readable_code text,
  signature_value text,
  chain_value text,
  previous_receipt_id text,
  reversal_of_receipt_id text,
  is_start_receipt boolean NOT NULL DEFAULT false,
  is_year_receipt boolean NOT NULL DEFAULT false,
  is_dummy_receipt boolean NOT NULL DEFAULT false,
  is_reversal_receipt boolean NOT NULL DEFAULT false,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  chain_previous_receipt_id text,
  chain_previous_hash text,
  receipt_payload_canonical text,
  receipt_payload_hash text,
  signature_algorithm text,
  signature_created_at timestamp with time zone,
  signature_state text DEFAULT 'PENDING'::text,
  verification_status text,
  verification_checked_at timestamp with time zone,
  verification_notes text,
  CONSTRAINT fiscal_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_fiscal_receipts_cash_register FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id),
  CONSTRAINT fk_fiscal_receipts_sales_order FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT fk_fiscal_receipts_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fk_fiscal_receipts_previous_receipt FOREIGN KEY (previous_receipt_id) REFERENCES public.fiscal_receipts(id),
  CONSTRAINT fk_fiscal_receipts_reversal_of_receipt FOREIGN KEY (reversal_of_receipt_id) REFERENCES public.fiscal_receipts(id)
);
CREATE TABLE public.form_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  schema_json jsonb NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  CONSTRAINT form_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.google_calendar_connections (
  user_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'google'::text,
  refresh_token text NOT NULL,
  access_token text,
  token_type text,
  expiry timestamp with time zone,
  scope text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT google_calendar_connections_pkey PRIMARY KEY (user_id),
  CONSTRAINT google_calendar_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.google_oauth_tokens (
  user_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'google'::text,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  scope text,
  token_type text,
  refresh_token_expires_in integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_calendar_id text,
  enabled_calendar_ids ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT google_oauth_tokens_pkey PRIMARY KEY (user_id),
  CONSTRAINT google_oauth_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.intake_forms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  person_id uuid NOT NULL,
  customer_profile_id uuid,
  template_id uuid,
  template_version integer NOT NULL DEFAULT 1,
  answers_json jsonb NOT NULL,
  signature_storage_path text,
  pdf_storage_path text,
  signed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  schema_json jsonb,
  status text NOT NULL DEFAULT 'draft'::text,
  CONSTRAINT intake_forms_pkey PRIMARY KEY (id),
  CONSTRAINT intake_forms_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT intake_forms_customer_profile_id_fkey FOREIGN KEY (customer_profile_id) REFERENCES public.customer_profiles(id),
  CONSTRAINT intake_forms_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.form_templates(id),
  CONSTRAINT intake_forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.invoice_counters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  year integer NOT NULL,
  last_number integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_counters_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  service_id uuid,
  title text NOT NULL,
  qty numeric NOT NULL DEFAULT 1,
  unit_price_cents integer NOT NULL DEFAULT 0,
  line_total_cents integer NOT NULL DEFAULT 0,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.invoice_sequences (
  tenant_id uuid NOT NULL,
  year integer NOT NULL,
  last_number integer NOT NULL DEFAULT 0,
  CONSTRAINT invoice_sequences_pkey PRIMARY KEY (tenant_id, year)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  invoice_number text NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  person_id uuid NOT NULL,
  customer_snapshot jsonb NOT NULL,
  payment USER-DEFINED NOT NULL,
  total_cents integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::invoice_status,
  pdf_storage_path text,
  sent_to_email text,
  sent_at timestamp with time zone,
  paid_at timestamp with time zone,
  locked_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.oauth_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL,
  email text,
  refresh_token_encrypted text,
  access_token_encrypted text,
  expires_at timestamp with time zone,
  scopes text,
  default_calendar_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_allocations (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  payment_id text NOT NULL,
  invoice_id text,
  sales_order_id text,
  allocated_amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_allocations_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.payment_methods (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  fiscal_category USER-DEFINED NOT NULL,
  counts_as_cash_revenue boolean NOT NULL,
  requires_fiscal_receipt boolean NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  allows_refund boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  sales_order_id text,
  invoice_id text,
  cash_register_id text,
  payment_method_id text NOT NULL,
  amount numeric NOT NULL,
  currency_code text NOT NULL DEFAULT 'EUR'::text,
  direction USER-DEFINED NOT NULL DEFAULT 'INBOUND'::payment_direction,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::payment_status,
  paid_at timestamp with time zone,
  external_reference text,
  recorded_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  provider text DEFAULT 'MANUAL'::text,
  provider_transaction_id text,
  provider_response_json jsonb,
  failure_reason text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payments_sales_order FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT fk_payments_cash_register FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id),
  CONSTRAINT fk_payments_payment_method FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id)
);
CREATE TABLE public.persons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  phone text,
  email text,
  birthday date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT persons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.receipt_deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  fiscal_receipt_id text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['EMAIL'::text, 'WHATSAPP'::text])),
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'FAILED'::text])),
  recipient text,
  subject text,
  message_preview text,
  provider text,
  provider_message_id text,
  sent_by uuid,
  sent_at timestamp with time zone,
  failed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT receipt_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT receipt_deliveries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT receipt_deliveries_fiscal_receipt_id_fkey FOREIGN KEY (fiscal_receipt_id) REFERENCES public.fiscal_receipts(id),
  CONSTRAINT receipt_deliveries_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_order_lines (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  sales_order_id text NOT NULL,
  line_type text NOT NULL,
  reference_id text,
  name text NOT NULL,
  description text,
  quantity numeric NOT NULL,
  unit_price_gross numeric NOT NULL,
  discount_amount numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL,
  line_total_gross numeric NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sales_order_lines_sales_order FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.sales_orders (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  location_id text,
  appointment_id text,
  customer_id text,
  cash_register_id text,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::sales_order_status,
  currency_code text NOT NULL DEFAULT 'EUR'::text,
  subtotal_gross numeric NOT NULL DEFAULT 0,
  discount_total numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  grand_total numeric NOT NULL DEFAULT 0,
  created_by text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sales_orders_location FOREIGN KEY (location_id) REFERENCES public.business_locations(id),
  CONSTRAINT fk_sales_orders_cash_register FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  default_price_cents integer NOT NULL DEFAULT 0 CHECK (default_price_cents IS NULL OR default_price_cents >= 0),
  duration_minutes integer NOT NULL DEFAULT 60 CHECK (duration_minutes IS NULL OR duration_minutes > 0),
  buffer_minutes integer NOT NULL DEFAULT 0 CHECK (buffer_minutes IS NULL OR buffer_minutes >= 0),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.services_backup_2026_04_01 (
  id uuid,
  tenant_id uuid,
  name text,
  default_price_cents integer,
  duration_minutes integer,
  buffer_minutes integer,
  description text,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.signature_units (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  provider_name text NOT NULL,
  certificate_serial_number text NOT NULL,
  certificate_subject text,
  certificate_valid_from timestamp with time zone,
  certificate_valid_until timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::signature_unit_status,
  finanzonline_registered_at timestamp with time zone,
  replaced_by_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signature_units_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_message_mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  mentioned_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_message_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT team_message_mentions_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.team_messages(id)
);
CREATE TABLE public.team_message_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name text NOT NULL,
  emoji text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_message_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT team_message_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.team_messages(id)
);
CREATE TABLE public.team_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  text text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sender_name text,
  edited_at timestamp with time zone,
  deleted_at timestamp with time zone,
  file_name text,
  file_path text,
  file_type text,
  file_size bigint,
  CONSTRAINT team_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  display_name text NOT NULL,
  legal_name text NOT NULL,
  invoice_address_line1 text,
  invoice_address_line2 text,
  zip text,
  city text,
  country text DEFAULT 'Österreich'::text,
  phone text,
  email text,
  iban text,
  bic text,
  bank_name text,
  uid_optional text,
  kleinunternehmer_text text NOT NULL DEFAULT 'Gemäß § 6 Abs. 1 Z 27 UStG wird keine Umsatzsteuer berechnet.'::text,
  invoice_prefix text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mail_sender_name text,
  mail_reply_to_email text,
  mail_delivery_mode text DEFAULT 'tenant_email'::text CHECK (mail_delivery_mode = ANY (ARRAY['tenant_email'::text, 'oauth_user'::text, 'system_fallback'::text])),
  mail_is_active boolean NOT NULL DEFAULT true,
  mail_subject_template text,
  mail_body_template text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.time_off (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  label text NOT NULL DEFAULT 'Frei'::text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_off_pkey PRIMARY KEY (id),
  CONSTRAINT time_off_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  user_id uuid NOT NULL,
  tenant_id uuid,
  role USER-DEFINED NOT NULL DEFAULT 'PRACTITIONER'::user_role,
  full_name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  calendar_tenant_id uuid,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);